dist: trusty
language: java
jdk:
  - openjdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE yogogym;'
before_install:
  - export TZ=Spain/Madrid
script:
  - mvn test 
  - mvn test -Dspring.profiles.active=mysql-travis
